### ISSUE TITLE
USPTO AWS Web Application Firewall breaks Patent Public Search Functionality

### ISSUE THREAD

**Issue by robinfaber** [parkerhancock/patent_client#101]
Hi,

I'm trying to execute the example code from the docs, but keep running into JSONDecodeError:

```
from patent_client import Patent, PublishedApplication
Patent.objects.get("10000000")
```

Any idea on how to resolve this?

**Comment by parkerhancock** [comment]
The USPTO implemented a AWS Web Application Firewall as an anti-bot measure that is currently breaking this feature. I don't have a good workaround until the USPTO decides to offer an actual PublicSearch API. Sorry!

**Comment by parkerhancock** [comment]
Updated docs to indicate that this feature is broken, and updated examples. Will keep this open on the off chance that I can find a workaround.

**Comment by hoffmabc** [comment]
Is it just me or does that actual web site for Patent Public Search not working? Going to this URL for me just shows Forbidden in general.

https://ppubs.uspto.gov/pubwebapp/

**Comment by parkerhancock** [comment]
> Is it just me or does that actual web site for Patent Public Search not working? Going to this URL for me just shows Forbidden in general.
> 
> https://ppubs.uspto.gov/pubwebapp/

I think what you're experiencing is another side effect of the WAF. If you try to use this library a few times on Patent Public Search, your IP gets blacklisted for some short period of time. If you turn on a VPN, or wait a few hours, the Forbidden notice goes away.

I should probably hard-disable the PPS functionality in this library to prevent that from happening to other people...

**Comment by parkerhancock** [comment]
The WAF appears to be gone, and I've gotten it working by using the HTTPX library to support HTTP/2

The notes suggesting that Public Patent Search no longer works have been removed!

Version 3.2.7 includes these fixes!

**Comment by hoffmabc** [comment]
I'm seeing the following even on 3.2.7 @parkerhancock. Any thoughts?

INFO:httpx:HTTP Request: POST https://ppubs.uspto.gov/dirsearch-public/users/me/session "HTTP/2 403 Forbidden"

**Comment by parkerhancock** [comment]
I'll look into it.

**Comment by parkerhancock** [comment]
I can't reproduce that error. Are you still getting it? Try updating to the most recent version (3.2.9)

**Comment by parkerhancock** [comment]
This is working #119. Let me know if you're still having issues.

**Comment by Shagrath9212** [comment]
Still having similar issue.
Steps to reproduce: using TunnelBear, select the location United States, and run 
```PublishedApplicationBiblio.objects.get('20180235467')```
