### ISSUE TITLE
Assignment API; PriorOwnerName; Not found

### ISSUE THREAD

**Issue by Protimapaul** [parkerhancock/patent_client#107]
I was looking at assignment API

On USTPO assignment website I see field about "PriorOwnerName" Though I think we have "Collect all applications ever assigned out of the company" But I was unable to find a way to know specifically PriorOwnerName for a patent.

USTPO assignment APIhttps://patent-client.readthedocs.io/en/latest/user_guide/assignments.html

Please advise if there is any way.

**Comment by parkerhancock** [comment]
The assignment data isn't structured that way. Each assignment has an assignor (the party assigning rights), and an assignee (the party receiving rights), but you have to look at the chain and make a judgment call about who the proper owner is. Thanks!
