### ISSUE TITLE
.events is not needed and causes an error when calling .legal on a Inpadoc model

### ISSUE THREAD

**Issue by hoffmabc** [parkerhancock/patent_client#110]
Calling .legal on an Inpadoc model returned will give you: ListCollection' object has no attribute 'events'.

I believe .events in util.py is unnecessary. Without it the call returns an array of legal events successfully.

https://github.com/parkerhancock/patent_client/blob/e9238def2fce8440b1660f917ef25a8562fa4fd4/src/patent_client/epo/ops/util.py#L35

**Comment by parkerhancock** [comment]
Can you give me an example Inpadoc object? Happy to make this change, but I want to add a test case to make sure I'm getting the right behavior.

Thanks!

**Comment by parkerhancock** [comment]
Closed for lack of activity.
