### ISSUE TITLE
504 Gateway Time-out for PEDS

### ISSUE THREAD

**Issue by hoffmabc** [parkerhancock/patent_client#123]
This didn't seem to occur on the 3.x version, but I'm now getting a:

"Server error '504 Gateway Time-out' for url 'https://ped.uspto.gov/api/queries'\nFor more information check: https://httpstatuses.com/504"

when attempting to retrieve assignment data.

**Comment by parkerhancock** [comment]
That means PEDS is down. I think v.3 use to give a more informative error on that one, I'll add it back.

Just FYI, the PED's backend is super-flakey, and tends to be most flakey on Mondays. No idea why - just how the cookie crumbles. Try retrying your request.
