### ISSUE TITLE
Not getting the inventor details.

### ISSUE THREAD

**Issue by amit-trexo** [parkerhancock/patent_client#128]
Hi,
While querying the US application number 17937771, i am getting no inventors.
Please check.

Thanks
Amit

**Comment by parkerhancock** [comment]
Hey! Thanks for the issue. It's not a problem with patent client, but one with upstream USPTO data. In the screenshot below (Taken from the PEDS client application that feeds patent client), that application number shows no inventors.

![image](https://github.com/parkerhancock/patent_client/assets/633163/9c0b41cf-922a-4d55-8531-b418420bf475)

That's incorrect, as that application names five inventors. But I can't fix the USPTO's data. Thanks!
