### ISSUE TITLE
Docker weirdness; GlobalDossierApplication missing 'office_actions' attribute

### ISSUE THREAD

**Issue by KennethThompson** [parkerhancock/patent_client#131]
I began developing with patent_client in a VS code dev container.  For some reason, the dockerized version of the code does not include 'office_actions' as an attribute for the fetched GlobalDossierApplication. I've confirmed that the patent_client module is installed in the docker image (and even my last pull version), but no good. I even confirmed that the source code for patent_client includes the attribute code.  When I run the same code outside of docker, the attribute is present. Very odd- not sure what would cause the office_action attribute to be missing- any thoughts?

Happy to gen up an example VS code project with dockerized support to ease testing on your end- just let me know.

Thanks!

**Comment by parkerhancock** [comment]
That is odd! I don't know why that would be happening. Can you give me the output of what `dir` gives you on a Global DossierApplication object? That might provide a clue.

**Comment by parkerhancock** [comment]
I'm hopeful that #133 will resolve this and other similar bugs introduced into the library by my wonky attempt to provide async support.

**Comment by kt1135** [comment]
> I'm hopeful that #133 will resolve this and other similar bugs introduced into the library by my wonky attempt to provide async support.

Some good news- the docker issue was resolved with an environment variable:
ENV PYDEVD_WARN_SLOW_RESOLVE_TIMEOUT=30

This sets the debug timeout above 0.5s, which is needed given that the async request for the attributes takes a few seconds.

I'll post on the other ticket regarding async changes

**Comment by KennethThompson** [comment]
You can close this ticket.  I'll reopen if a new docker issue emerges after #133 is fixed
