### ISSUE TITLE
Confirmation Number Missing

### ISSUE THREAD

**Issue by amit-trexo** [parkerhancock/patent_client#135]
![MicrosoftTeams-image (13)](https://github.com/parkerhancock/patent_client/assets/127986408/4d27bae4-8522-4f87-813b-bc790df63f35)
Hi,
  I am not able to find the confirmation number field in the response of
  USApplication.objects.get(application_number). Attached is the peds response for the same.
  It would be helpful, if i am getting this field in the response.

Thanks
Amit

**Comment by amit-trexo** [comment]
Hi,
 Any update on this?

Thanks
Amit

**Comment by parkerhancock** [comment]
Hi @amit-trexo!

Thanks for the bug report. Happy to review a PR to resolve this issue. My development time on the library is fully occupied with #133 

Thanks!

Parker

**Comment by amit-trexo** [comment]
Hi,
 I am still not getting the confirmation number.

**Comment by parkerhancock** [comment]
Resolved in v5.0.3

**Comment by amit-trexo** [comment]
Hi Parker,
   It seems we are now getting fewer fields now, I do not see attorney details + parent child continuity etc.
   Please check, we are now getting the confirmation number but missing the other details which were coming in V4.1.10

Thanks
