### ISSUE TITLE
Option to avoid loading national codes

### ISSUE THREAD

**Issue by recurvelabs** [parkerhancock/patent_client#136]
On initialization, patent client downloads a spreadsheet to build a local database for these.   This is maybe okay as a once off but I'm using this on a cloud run instance (serverless) which doesn't have a disk plus it has to do this each time the server starts which delays startup causing health failures and probably annoys whoever is hosting the spreadsheet.

**Comment by parkerhancock** [comment]
Hi @recurvelabs! 

That sounds like a good enhancement! Happy to review a PR to implement this.

I'm thinking the easier approach here would be to defer loading national codes until the Inpadoc legal endpoint is called. And that would be a very useful improvement!

Thanks!

**Comment by parkerhancock** [comment]
This has been implemented in v5. If you try to access the legal codes attribute on an EPO doc, it will build the DB. If you leave that feature alone - no DB!
