### ISSUE TITLE
When using docker, Inpadoc client credentials fail to be identified

### ISSUE THREAD

**Issue by KennethThompson** [parkerhancock/patent_client#141]
When running in docker, patent_client is unable to find the .patent_client_config.yaml in the ~ directory, and manually setting the environment variables does not correct the issue either.

I've had to hard code in the secret/key to get the inapdoc client working in docker for now.  

Let me know if you need assistance recreating this issue.

Thanks!

**Comment by moraneden** [comment]
Any idea how to workaround it for now?

**Comment by parkerhancock** [comment]
Hey! Is this still an issue if you set the environment variables `PATENT_CLIENT_EPO_API_KEY `and `PATENT_CLIENT_EPO_API_SECRET`?

Starting in v4 and now v5, I use `pydantic-settings` under the hood, so all patent_client settings are driven from environment variables prefixed with `PATENT_CLIENT_`
