### ISSUE TITLE
can't run program when importing library

### ISSUE THREAD

**Issue by gargparthb** [parkerhancock/patent_client#142]
After installing via pip, after I try to run my program that only imports the module, the program won't terminate.

**Comment by amit-trexo** [comment]
Any update on this ? Even i am getting this, are there any circular dependencies or library is stuck in some event loop?

**Comment by parkerhancock** [comment]
Try `pip install --upgrade patent_client` to get v5.0.1 and let me know if you're still having issues. If so, please provide a tracefile / error so I can see what's going on!
