### ISSUE TITLE
Public patent search API no longer working - USPTO blocking programmatic access?

### ISSUE THREAD

**Issue by Hobly** [parkerhancock/patent_client#143]
As of yesterday I have been unable to make any successful requests via the public patent search URL: https://ppubs.uspto.gov/pubwebapp.

Anyone else having issues?

**Comment by recurvelabs** [comment]
Took a look this morning, sadly it now looks like you need to authorize with a 'X-Access-Token' fetched via a POST to https://ppubs.uspto.gov/dirsearch-public/users/me/session and the path to get documents after a search has slightly changed as well to include the word 'internal'.

**Comment by Akshit-Carboledger** [comment]
@recurvelabs How to get this access token?

**Comment by parkerhancock** [comment]
Fixed in v5. 

Note that the Public Patent Search is still very limited in terms of data access frequency. If you abuse the endpoint, you will start to get error codes as the USPTO tries to throttle you!
