### ISSUE TITLE
Is there lots broken? .claims_text and 'help()' doesn't work, some USPTO searching too

### ISSUE THREAD

**Issue by legolego** [parkerhancock/patent_client#149]
Hello,
I just installed and re-installed the patent_client library, on python 3.11. I'm going through example I have found with the goal of getting to US patent claims text. So far, help() is broken:
`help(USApplication)`

yields:
`UnmanagedModelException: Unable to find manager for PEDSBaseModel, looked in patent_client.uspto.peds.manager.PEDSBaseModelManager`

`Patent.objects.get("9209631")` gives: `HTTPStatusError: Client error '429 Too Many Requests' for url...`

`PublishedApplication.objects.get("9209631")` gives: `HTTPStatusError: Client error '401 Unauthorized' for url...`

I'm not sure if I'm doing everything wrong, are there working examples of how to get claims_text for a patent number/application?
Thank you!

**Comment by parkerhancock** [comment]
Try upgrading to v5 and let me know if you are still having issues. v5 should be the best bet here! But let me know if you still have problems.
