### ISSUE TITLE
Assignment model fails to fetch any data

### ISSUE THREAD

**Issue by david-lightbringer** [parkerhancock/patent_client#167]
No examples from doc is working, all failing with `httpx.ConnectError: [Errno 8] nodename nor servname provided, or not known`

Is USPTO swapping api perhaps? 
I cannot access the original API URL either: https://assignment-api.uspto.gov/documentation-patent

Minimal example: `from patent_client import Assignment; assignment = Assignment.objects.filter(patent_number='9534285')`

Python version: 3.12
Patent client version: 5.0.13
OS: macOS 14.3

**Comment by parkerhancock** [comment]
Huh. The link to the API documentation has been wiped from the USPTO website. 

"https://assignment.uspto.gov/patent/index.html#/patent/search"

I think this is an upstream problem. Sorry for the inconvenience!

**Comment by david-lightbringer** [comment]
Huh, maybe they did some maintenance, the minimal example works again now. 

I'll close this issue. Thanks!
