### ISSUE TITLE
ValueError: ODP API key is not set

### ISSUE THREAD

**Issue by ishu121992** [parkerhancock/patent_client#177]
Below is my simple code: 
from patent_client.odp import USApplicationBiblio
from dotenv import load_dotenv
import os

load_dotenv()  # Load variables from .env file

api_key = os.getenv('PATENT_CLIENT_ODP_API_KEY')  # Fetch the API key

if not api_key:
    raise ValueError("ODP API key is not set")

app = USApplicationBiblio.objects.get("16123456")  # Retrieve application

I HAVE TRIED SLIGHT VARIATIONS AS WELL (like ODP_API_KEY), but it doesn't work. 

Getting Error: 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[5], line 1
----> 1 app = USApplicationBiblio.objects.get("16123456")  # Retrieve application

File [~/.local/lib/python3.10/site-packages/patent_client/util/pydantic_util.py:47](http://localhost:8888/lab/tree/Learning/lang/~/.local/lib/python3.10/site-packages/patent_client/util/pydantic_util.py#line=46), in ClassProperty.__get__(self, instance, owner)
     46 def __get__(self, instance, owner):
---> 47     return self.getter(owner)

File [~/.local/lib/python3.10/site-packages/patent_client/util/pydantic_util.py:91](http://localhost:8888/lab/tree/Learning/lang/~/.local/lib/python3.10/site-packages/patent_client/util/pydantic_util.py#line=90), in BaseModel.objects(cls)
     89     manager_module = cls.__module__.split(".model")[0] + ".manager"
     90     manager_path = manager_module + "." + cls.__name__ + "Manager"
---> 91 return get_class(manager_path, base_class=cls)()

File [~/.local/lib/python3.10/site-packages/patent_client/util/pydantic_util.py:72](http://localhost:8888/lab/tree/Learning/lang/~/.local/lib/python3.10/site-packages/patent_client/util/pydantic_util.py#line=71), in get_class(class_name, base_class)
     70 module_name, class_name = absolute_model_name.rsplit(".", 1)
     71 try:
---> 72     module = importlib.import_module(module_name)
     73     return getattr(module, class_name)
     74 except (ImportError, AttributeError) as e:

File /usr/lib/python3.10/importlib/__init__.py:126, in import_module(name, package)
    124             break
    125         level += 1
--> 126 return _bootstrap._gcd_import(name[level:], package, level)

File <frozen importlib._bootstrap>:1050, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:1027, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:1006, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:688, in _load_unlocked(spec)

File <frozen importlib._bootstrap_external>:883, in exec_module(self, module)

File <frozen importlib._bootstrap>:241, in _call_with_frames_removed(f, *args, **kwds)

File [~/.local/lib/python3.10/site-packages/patent_client/_sync/uspto/odp/manager.py:29](http://localhost:8888/lab/tree/Learning/lang/~/.local/lib/python3.10/site-packages/patent_client/_sync/uspto/odp/manager.py#line=28)
     16 if tp.TYPE_CHECKING:
     17     from .model import (
     18         Assignment,
     19         Continuity,
   (...)
     27         USApplicationBiblio,
     28     )
---> 29 api = ODPApi()
     32 class USApplicationManager(Manager):
     33     default_filter = "appl_id"

File [~/.local/lib/python3.10/site-packages/patent_client/_sync/uspto/odp/api.py:38](http://localhost:8888/lab/tree/Learning/lang/~/.local/lib/python3.10/site-packages/patent_client/_sync/uspto/odp/api.py#line=37), in ODPApi.__init__(self)
     36 def __init__(self):
     37     if SETTINGS.odp_api_key is None:
---> 38         raise ValueError("ODP API key is not set")
     39     self.client = PatentClientSession(headers={"X-API-KEY": SETTINGS.odp_api_key})

ValueError: ODP API key is not set

**Comment by david-lightbringer** [comment]
You'll need to load your dot-env before any import of patent client. So move the load before the patent-client import and try it!

**Comment by Hobly** [comment]
Just to double check the obvious: you do have a .env file that contains your api key right? :)
