### ISSUE TITLE
version 2.0 no longer supports PtabTrial?

### ISSUE THREAD

**Issue by samkorte** [parkerhancock/patent_client#34]
The docs need to be updated to reflect that "PtabTrial" is no longer used:

>>> import patent_client
>>> patent_client.__version__
'2.0.1'
>>> from patent_client import PtabTrial
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'PtabTrial' from 'patent_client' 

Looks like PtabProceeding can replace PtabTrial in the old documentation and everything works fine.

**Comment by parkerhancock** [comment]
Thanks for leaving this bug! Lots of stability improvements in 2.0, but the docs need a lot of work. That change was motivated by the fact that the USPTO changed the underlying API to include non-trial PTAB proceedings (patent appeals and such), so I generalized the model name.

https://developer.uspto.gov/api-catalog/ptab-api-v2

Doc changes are coming though. Hopefully COVID-19 will give me some time to do that kind of maintenance.
