### ISSUE TITLE
"There is a USPTO problem"

### ISSUE THREAD

**Issue by samkorte** [parkerhancock/patent_client#38]
Did the PTO change or disable the API?  I get "There is a USPTO problem"  when using USApplication

>>> from patent_client import USApplication
>>> app = USApplication.objects.get('15710770')
>>>.....manager.py", line 149, in is_online
             raise NotAvailableException("There is a USPTO problem")

Edit:  looks like it's a USPTO issue:

https://ped.uspto.gov/peds/
https://www.uspto.gov/blog/ebiz/

Patent Examination Data System (PEDS) and PEDS API down (out-of-service)
The USPTO is experiencing an issue with PEDS and is working diligently to resolve the issue

**Comment by parkerhancock** [comment]
Thanks for reporting the issue - The library appropriately reported an issue with the underlying API. Thanks!
