### ISSUE TITLE
Biblio data not pulling for certain patents

### ISSUE THREAD

**Issue by appdl2021** [parkerhancock/patent_client#41]
Thanks very much for this library, it is great to pull data from the EPO!  For some reason there are certain patents that error out when I'm trying to pull biblio data for them.  Am I just not using the tool correctly, or is this maybe a known issue?  Below shows my code and error message.  Here is a link to the actual patent on the EPO website... https://worldwide.espacenet.com/patent/search/family/030117972/publication/JP2005533465A?q=JP2005533465A.

Thanks in advance for any help!

```
from patent_client import Patent, PublishedApplication, Inpadoc
Inpadoc.objects.get('JP2005533465A').biblio
```

Gives me this error...

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-319-b5366a15b586> in <module>
----> 1 Inpadoc.objects.get('JP2005533465A').biblio

/usr/local/lib/python3.7/site-packages/patent_client/util/related.py in get(self)
     16             filter_obj = {k: getattr(self, v) for (k, v) in mapping.items()}
     17             logger.debug(f'Fetching related {klass} using filter {filter_obj}')
---> 18             return resolve(klass.objects.get(**filter_obj), attribute)
     19         except AttributeError:
     20             return None

/usr/local/lib/python3.7/site-packages/patent_client/util/manager.py in get(self, *args, **kwargs)
    175         if len(manager) > 1:
    176             raise ValueError("More than one document found!")
--> 177         return manager[0]  # type: ignore
    178 
    179     # Manager Functions

/usr/local/lib/python3.7/site-packages/patent_client/util/manager.py in __getitem__(self, key)
    125             mger = mger.limit(stop - start)
    126             return mger
--> 127         return self.offset(key).first()
    128 
    129     def filter(self, *args, **kwargs) -> Manager[ModelType]:

/usr/local/lib/python3.7/site-packages/patent_client/util/manager.py in first(self)
    185     def first(self) -> ModelType:
    186         """Get the first object in the manager"""
--> 187         return next(iter(self))
    188 
    189     def all(self) -> Manager[ModelType]:

/usr/local/lib/python3.7/site-packages/patent_client/util/manager.py in __iter__(self)
     93                 yield item
     94             # Yield out of the iterator, expanding the cache as you go.
---> 95             for item in self.__result_iterator__:
     96                 self.__cache__.append(item)
     97                 yield item

/usr/local/lib/python3.7/site-packages/patent_client/epo/inpadoc/manager.py in _get_results(self)
     94                 break
     95             if counter >= offset:
---> 96                 yield self.schema.load(item)
     97 
     98     @property

/usr/local/lib/python3.7/site-packages/marshmallow/schema.py in load(self, data, many, partial, unknown)
    726         """
    727         return self._do_load(
--> 728             data, many=many, partial=partial, unknown=unknown, postprocess=True
    729         )
    730 

/usr/local/lib/python3.7/site-packages/marshmallow/schema.py in _do_load(self, data, many, partial, unknown, postprocess)
    848             try:
    849                 processed_data = self._invoke_load_processors(
--> 850                     PRE_LOAD, data, many=many, original_data=data, partial=partial
    851                 )
    852             except ValidationError as err:

/usr/local/lib/python3.7/site-packages/marshmallow/schema.py in _invoke_load_processors(self, tag, data, many, original_data, partial)
   1099             many=many,
   1100             original_data=original_data,
-> 1101             partial=partial,
   1102         )
   1103         return data

/usr/local/lib/python3.7/site-packages/marshmallow/schema.py in _invoke_processors(self, tag, pass_many, data, many, original_data, **kwargs)
   1225                     data = processor(data, original_data, many=many, **kwargs)
   1226                 else:
-> 1227                     data = processor(data, many=many, **kwargs)
   1228         return data
   1229 

/usr/local/lib/python3.7/site-packages/patent_client/epo/inpadoc/schema.py in pre_load(self, data, *args, **kwargs)
    189             data["title"] = titles
    190         else:
--> 191             data["title"] = titles["#text"]
    192         return data
    193 

TypeError: 'NoneType' object is not subscriptable`

**Comment by parkerhancock** [comment]
Hey! Thanks for the interest! It looks like the application that you pulled doesn't have a title attribute - or at least not one in the Inpadoc database. The library has made a mistaken assumption that the case you're looking at has a title field.  I suspect it has something to do with the fact that it is a Japanese reference. The INPADOC standard tends to break down a bit for east asian languages that don't use the latin alphabet (or its derivatives).

The easy fix would be to change line 191 to be:

```python
data["title"] = titles.get("#text", None)
```

That would fail gracefully, setting the title attribute to ```None``` in the event it doesn't have a detectable title. Would be happy to review and approve a corresponding PR, but it will be a while before I can get to this due to other real-life commitments. Thanks!

**Comment by appdl2021** [comment]
Thanks!  This is helpful!  For now I think I can just use a try/except understanding why this is happening.  Appreciate it!
