### ISSUE TITLE
"query" keyword for filter doesn't appear to work for applications

### ISSUE THREAD

**Issue by drmatthewclark** [parkerhancock/patent_client#79]
querying using the "query" keyword doesn't seem to work. 

>>> tennis_patents = USApplication.objects.filter(query="TTL/steel")
>>> len(tennis_patents)
0

**Comment by parkerhancock** [comment]
Hey! The query for the USApplication object works a bit differently. It's supported by the [USPTO's PEDS Database](https://ped.uspto.gov/peds/#!/). It uses [Solr search syntax](https://solr.apache.org/guide/6_6/common-query-parameters.html#common-query-parameters), and I'm not even sure that I've baked in a query feature to USApplications. 

You should be able to do what you're looking for with the search

```python

tennis_patents = USApplication.objects.filter(title="steel")

```
