### ISSUE TITLE
Question; is there any way to use EPO to download CMS objects such as IDS pdfs from US cases

### ISSUE THREAD

**Issue by KennethThompson** [parkerhancock/patent_client#83]
I've looked through the documentation, and even the pull request that includes EPO register search functionality.  However, I was unable to identify how I might access the global dossier for US applications through the EPO register.  When I search the EPO register via chrome, I can see the entire list of CMS objects from the US file wrapper for my cases of interests.  Is there any way of accessing this list of CMS objects and executing a download via the API?  Now that PEDs blocks downloads, it would be great if there was an alternative way to grab PDFs from the file wrappers of US cases ...

Thanks very much!

**Comment by parkerhancock** [comment]
Hey Kenneth!

Thanks for the question. Can you give me a link to where on the EPO website you are seeing Global Dossier documents? I'd love to take a look.

The USPTO doesn't offer an API for what you're looking for (As you say, PEDS CMS should, but doesn't). And the API's available through the EPO are broken down into INPADOC/Espacenet (which don't include file histories), and the EP Register (which only includes EP files).

There are a few ways you could get what you're looking for - that aren't included in patent_client (yet!). You could automate the API backing the [USPTO's global dossier](https://globaldossier.uspto.gov/#/), or automate [Patent Center](https://patentcenter.uspto.gov/). But both are undocumented. I have code I personally use to scrape Patent Center, but it's complex, and not reliable enough to be included in Patent Client. 

Sorry there isn't an easy answer here!

**Comment by KennethThompson** [comment]
> 

See [link](https://register.epo.org/ipfwretrieve?apn=US.202117343042.A&lng=en)

There are work arounds for patent center I have found as well- but that option could be removed at any moment.  I was hoping the EPO api would enable access to the global dossier documents.  Thanks for the assistance.

**Comment by parkerhancock** [comment]
Hey! There's a way to do this now. I just added support for the USPTO's global dossier implementation. Check the docs here: [Global Dossier](https://patent-client.readthedocs.io/en/latest/user_guide/global_dossier.html)

Just update to v3.2.0, then:

```python
from patent_client import GlobalDossierApplication
app = GlobalDossierApplication.objects.get("<US Application ID")
app.documents # produces a list of all available documents
app.documents[0].download(path="folder") # downloads the file to specified folder
```

Thanks!

**Comment by KennethThompson** [comment]
> Hey! There's a way to do this now. I just added support for the USPTO's global dossier implementation. Check the docs here: [Global Dossier](https://patent-client.readthedocs.io/en/latest/user_guide/global_dossier.html)
> 
> Just update to v3.2.0, then:
> 
> ```python
> from patent_client import GlobalDossierApplication
> app = GlobalDossierApplication.objects.get("<US Application ID")
> app.documents # produces a list of all available documents
> app.documents[0].download(path="folder") # downloads the file to specified folder
> ```
> 
> Thanks!

YOU ARE MY HERO.  When I saw you closed this item the other day my heart sank.  Very much appreciate your work on this.  Can't thank you enough.  I will be testing the changes very shortly.
