### ISSUE TITLE
"yankee.json.schema"

### ISSUE THREAD

**Issue by ioneme** [parkerhancock/patent_client#86]
It's a pleasure to greet you again.

During the example, an error occurred, too.

- error - 
File C:\Python311\Lib\site-packages\patent_client\util\json.py:2
      1 from yankee.json import Schema as BaseSchema
----> 2 from yankee.json.schema.fields import List as BaseListField
      4 from .schema_mixin import ListManagerMixin
      5 from .schema_mixin import PatentSchemaMixin

ModuleNotFoundError: No module named 'yankee.json.schema.fields'

**Comment by parkerhancock** [comment]
What version are you using? Make sure you're on v.3.0.6. Thanks!
