### ISSUE TITLE
to_pandas - TypeError

### ISSUE THREAD

**Issue by caiyishu** [parkerhancock/patent_client#96]
Thank you for providing such a helpful package. I have encountered an issue while using the `to_pandas` function to convert the results to a DataFrame. Specifically, I am receiving a `TypeError` message with the following error: `ForeignPriority.__init__() missing 1 required positional argument: 'country_name'` or `ParserError: year 0 is out of range: 0000-12-30T00:00:00Z`

I have attempted to filter the results with more conditions, which has worked for smaller results, but I am concerned that a longer result may still cause this issue.

I was wondering if there is a more efficient way to handle this issue or if you have any suggestions on how to approach this problem.

Thank you again for your assistance.

```
apps = USApplication.objects.filter(first_named_applicant=f'{Firmname}')

df = apps.to_pandas()
df.to_csv("./output.csv")
```

---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> Cell In[53], line 1
> ----> 1 df = google_apps.to_pandas()
>       2 df.to_csv("./google3.csv")
>
> File c:\Users\.conda\envs\patent_data\lib\site-packages\yankee\data\collection.py:50, in Collection.to_pandas(self, annotate)
>      47 import pandas as pd
>      49 list_of_series = list()
> ---> 50 for i in iter(self):
>      51     try:
>      52         series = i.to_pandas()
>
> File c:\Users\.conda\envs\patent_data\lib\site-packages\patent_client\util\base\manager.py:63, in Manager.__iter__(self)
>      62 def __iter__(self) -> Iterator[ModelType]:
> ---> 63     for item in self._get_results():
>      64         yield item
>
> File c:\Users\.conda\envs\patent_data\lib\site-packages\patent_client\uspto\peds\manager.py:58, in USApplicationManager._get_results(self)
>      56 for item in page_data["docs"]:
>      57     if not self.config.limit or counter < self.config.limit:
> ---> 58         yield self.__schema__.load(item)
>      59     counter += 1
>      60 page_num += 1
>
> File c:\Users\.conda\envs\patent_data\lib\site-packages\yankee\json\schema\schema.py:9, in Schema.load(self, obj)
>       7 def load(self, obj):
>       8     if self.name is not None or isinstance(obj, dict):
> ----> 9         return super().load(obj)
>      10     elif isinstance(obj, str):
>      11         return super().load(json.loads(obj))
>
> File c:\Users\.conda\envs\patent_data\lib\site-packages\yankee\base\deserializer.py:55, in Deserializer.load(self, obj)
>      53 def load(self, obj):
>      54     self.raw = obj
> ---> 55     return self._load_func(obj)
>
> File c:\Users\.conda\envs\patent_data\lib\site-packages\toolz\functoolz.py:489, in Compose.__call__(self, *args, **kwargs)
>     487 ret = self.first(*args, **kwargs)
>     488 for f in self.funcs:
> --> 489     ret = f(ret)
>     490 return ret
>
> File c:\Users\.conda\envs\patent_data\lib\site-packages\yankee\base\schema.py:67, in Schema.deserialize(self, obj)
>      65 obj = self.accessor(obj)
>      66 for key, field in self.fields.items():
> ---> 67     value = field.load(obj)
>      68     # If there is no value, don't include anything in the output dictionary
>      69     if not is_valid(value):
>
> File c:\Users\.conda\envs\patent_data\lib\site-packages\yankee\base\fields.py:238, in List.load(self, obj)
>     236     return ListCollection()
>     237 obj_gen = (self.item_schema.load(i) for i in obj)
> --> 238 return ListCollection(o for o in obj_gen if is_valid(o))
>
> File c:\Users\.conda\envs\patent_data\lib\site-packages\yankee\base\fields.py:238, in <genexpr>(.0)
>     236     return ListCollection()
>     237 obj_gen = (self.item_schema.load(i) for i in obj)
> --> 238 return ListCollection(o for o in obj_gen if is_valid(o))
>
> File c:\Users\.conda\envs\patent_data\lib\site-packages\yankee\base\fields.py:237, in <genexpr>(.0)
>     235 if not obj:
>     236     return ListCollection()
> --> 237 obj_gen = (self.item_schema.load(i) for i in obj)
>     238 return ListCollection(o for o in obj_gen if is_valid(o))
>
> File c:\Users\.conda\envs\patent_data\lib\site-packages\yankee\json\schema\schema.py:9, in Schema.load(self, obj)
>       7 def load(self, obj):
>       8     if self.name is not None or isinstance(obj, dict):
> ----> 9         return super().load(obj)
>      10     elif isinstance(obj, str):
>      11         return super().load(json.loads(obj))
>
> File c:\Users\.conda\envs\patent_data\lib\site-packages\yankee\base\deserializer.py:55, in Deserializer.load(self, obj)
>      53 def load(self, obj):
>      54     self.raw = obj
> ---> 55     return self._load_func(obj)
>
> File c:\Users\.conda\envs\patent_data\lib\site-packages\toolz\functoolz.py:489, in Compose.__call__(self, *args, **kwargs)
>     487 ret = self.first(*args, **kwargs)
>     488 for f in self.funcs:
> --> 489     ret = f(ret)
>     490 return ret
>
> File c:\Users\.conda\envs\patent_data\lib\site-packages\yankee\base\schema.py:80, in Schema.load_model(self, obj)
>      79 def load_model(self, obj):
> ---> 80     return self.__model__(**obj)
>
> TypeError: ForeignPriority.__init__() missing 1 required positional argument: 'country_name'

**Comment by caiyishu** [comment]
Although my solution is a little bit inefficient, the coding is as follows:

```
apps = USApplication.objects.filter(first_named_applicant='firmname')

num_start = 0
num_stop = len(apps)
num_step = 1000
list_i = range(num_start, num_stop + num_step, num_step)
list_ranges = [(list_i[i], min(list_i[i+1], num_stop)) for i in range(len(list_i)-1)]

for list_i in list_ranges:
    apps[list_i[0]:list_i[1]].to_pandas().to_csv(f'apps_{list_i[0]}-{list_i[1]}.csv', index=False)
```

**Comment by parkerhancock** [comment]
Thanks for identifying this error! I'll push a fix soon. At the moment, I have to wait for PEDS to come back online to make sure  my fix works! Thanks!

**Comment by caiyishu** [comment]
> Although my solution is a little bit inefficient, the coding is as follows:
> 
> ```
> apps = USApplication.objects.filter(first_named_applicant='firmname')
> 
> num_start = 0
> num_stop = len(apps)
> num_step = 1000
> list_i = range(num_start, num_stop + num_step, num_step)
> list_ranges = [(list_i[i], min(list_i[i+1], num_stop)) for i in range(len(list_i)-1)]
> 
> for list_i in list_ranges:
>     apps[list_i[0]:list_i[1]].to_pandas().to_csv(f'apps_{list_i[0]}-{list_i[1]}.csv', index=False)
> ```
> 
> Then manually skip the part that causes the error in the loop statement.

Sorry.
I found that this method does not work, as I discovered that each loop returns the same results. This means that apps[1:100] is exactly the same as apps[100:200].

**Comment by parkerhancock** [comment]
Should be fixed in v.3.2.4. Thanks!
