### ISSUE TITLE
Exception when calling GlobalDossierApplication.objects.get() on certain applications;"GlobalDossierApplication.init() got an unexpected keyword argument 'applicant_names'"

### ISSUE THREAD

**Issue by KennethThompson** [parkerhancock/patent_client#99]
For App Ser. No. 17193105, there is a single terminal disclaimer in the file wrapper. The identifier of the PDF is L512M7SNGREENX2

EDIT:  When I call:  app = GlobalDossierApplication.objects.get('16740760', type="application", office="US")

I am getting the attached exception.  This is happening across applications and not just the 1 that initially was reproducing this error. Please let me know what else I can provide to help troubleshoot.

Thanks very much!

"GlobalDossierApplication.__init__() got an unexpected keyword argument 'applicant_names'"

![image](https://user-images.githubusercontent.com/3701133/231290615-3ca4a4e7-bdaf-4823-a807-58570b110162.png)

**Comment by parkerhancock** [comment]
Probably a change to the underlying API. Since this is automating the GUI, it's prone to breakage anytime the update the website. I'll look into it!

**Comment by parkerhancock** [comment]
Try upgrading to `v3.2.3` and see if you still get the error. If so, can you provide me the entire text to reproduce it? I think I found a typo in the source code that may have been the problem, but I was not able to exactly reproduce this error.
